(function(g){var window=this;'use strict';var x4=function(a){a.oa("cardstatechange",a.rk()&&a.zo()?1:0)},y4=function(a,b){var c=g.Pa(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},Rcb=function(a){var b=g.hn(a);
a=g.ln(a);return new g.Xm(b.x,b.y,a.width,a.height)},B4=function(a){a=g.Ua(a);
delete z4[a];g.cd(z4)&&A4&&A4.stop()},Tcb=function(){A4||(A4=new g.Qp(function(){Scb()},20));
var a=A4;a.isActive()||a.start()},Scb=function(){var a=g.Ya();
g.Sc(z4,function(b){Ucb(b,a)});
g.cd(z4)||Tcb()},C4=function(a,b,c,d){g.jq.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.K=b;this.duration=c;this.D=d;this.coords=[];this.progress=this.J=0;this.C=null},Ucb=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.J=1E3/(b-a.C);a.C=b;Vcb(a,a.progress);1==a.progress?(a.j=0,B4(a),a.onFinish(),a.Kq()):a.hd()&&a.VI()},Vcb=function(a,b){"function"===typeof a.D&&(b=a.D(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.K[c]-a.u[c])*b+a.u[c]},Wcb=function(a,b){g.tb.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.J;this.state=b.j},D4=function(a,b,c,d,e){C4.call(this,b,c,d,e);
this.element=a},Xcb=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
D4.call(this,a,b,c,d,e)},Ycb=function(a){return Math.pow(a,3)},Zcb=function(a){return 3*a*a-2*a*a*a},$cb=function(a){g.D.call(this);
this.u=a||window;this.j=[]},E4=function(a){return a.baseUrl||null},F4=function(a,b){return g.fo(g.qm(a,b),function(c){return!!c})},adb=function(a,b,c){function d(X){var ma=X.hovercardButton;
if(!ma)return null;ma=ma.subscribeButtonRenderer;if(!ma)return null;var Y=f(ma.unsubscribedButtonText),Ca=f(ma.subscribedButtonText);if(ma.subscribed){var W=f(ma.subscriberCountWithUnsubscribeText);var Va=f(ma.subscriberCountText)}else W=f(ma.subscriberCountText),Va=f(ma.subscriberCountWithSubscribeText);var r=null;if(X.signinEndpoint){r=y4(X,"signinEndpoint","webNavigationEndpointData","url");if(!r){var P,pb;r=null==(pb=g.Q(null==(P=ma.signInEndpoint)?void 0:P.commandMetadata,g.r3))?void 0:pb.url}if(!r)return null}return Y&&
(Ca||r)?{subscribed:ma.subscribed,subscribeText:Y,subscribeCount:W,unsubscribeText:Ca,unsubscribeCount:Va,enabled:ma.enabled,signinUrl:r,classic:X.useClassicSubscribeButton}:null}
function e(X){if(X){var ma=[],Y=X.videoId;Y&&ma.push("v="+Y);(Y=X.playlistId)&&ma.push("list="+Y);(X=X.startTimeSeconds)&&ma.push("t="+X);return"/watch?"+ma.join("&")}}
function f(X){if(!X)return null;var ma=X.simpleText;return ma?ma:X.runs?g.qm(X.runs,function(Y){return Y.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,t=null,u=null,y=null,B=!1,G=null,M=null,N=null,H=null,U=null,aa=null;if("VIDEO"===h)g.Q(l,g.ZM)?m=g.Q(l,g.ZM).url:(aa=g.Q(l,g.YM),m=e(aa)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,t=f(p.text),p="LIVE"===p.style):t=f(b.videoDuration);else if("PLAYLIST"===h)g.Q(l,g.ZM)?m=g.Q(l,g.ZM).url:(aa=g.Q(l,g.YM),m=e(aa)),n=!1,q=a,u=f(b.playlistLength);else if("CHANNEL"===
h){if(B=y4(l,"browseEndpoint","browseId"))y=B,m="/channel/"+y;n=!1;q="new";(B=!!b.isSubscribe)?G=d(b):M=f(b.subscribersText)}else"WEBSITE"===h?((N=y4(l,"urlEndpoint","url"))&&(m=N),n=!0,q="new",N=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(U=f(b.additionalFeesText)),(n=y4(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=y4(b,"title","accessibility","accessibilityData","label");var da=b.endpoint?b.endpoint.clickTrackingParams:null,
ua="";if(b.metadata){var la=f(b.metadata);la&&(ua=la)}return{id:"element-"+c,type:h,title:f(b.title),metadata:ua,callToAction:f(b.callToAction),mT:b.image,iconUrl:N,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:t,lC:p,playlistLength:u,channelId:y,subscribeButton:G,subscribersText:M,isSubscribe:B,Ot:m||null,l4:n,sessionData:da?{itct:da}:null,f9:q,PA:a?a:null,isPlaceholder:b.isPlaceholder,
impressionUrls:F4(b.impressionUrls||[],E4),Y3:F4(b.hovercardShowUrls||[],E4),clickUrls:F4(l.loggingUrls||[],E4),visualElement:g.WE(b.trackingParams),productPrice:H,additionalFeesText:U,watchEndpoint:aa||null}},bdb=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:F4(a.impressionUrls||[],E4),elements:F4(a.elements||[],function(d,e){return adb(b,d,e)})};
a.trackingParams&&(c.visualElement=g.WE(a.trackingParams));return c},cdb=function(a){g.uT.call(this,a);
this.B=this.endscreen=null;this.j={};this.D={};this.C=this.u=null;this.K=[];this.ea=!0;this.J=0;a=a.W();this.V=g.UK(a)||"profilepage"===a.Ma;this.events=new g.lI(this);g.J(this,this.events);this.events.T(this.player,g.uE("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.vE("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.Gb);this.events.T(window,"focus",this.O7);this.load();var b=g.Ye("STYLE");(g.Le("HEAD")[0]||document.body).appendChild(b);g.ob(this,
function(){g.hf(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},ddb=function(a){return a.player.getVideoData().wd?"current":a.V?"new":"current"},G4=function(a){return"creator-endscreen-editor"===a.player.W().playerStyle},edb=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=bdb(f,ddb(a))));H4(a,f)},
urlParams:{v:c},withCredentials:!0};a.V&&(c.urlParams.ptype="embedded");var d=b.Ow;d&&(c.postParams={ad_tracking:d});if(b=g.Aya(b))if(b=g.de(b),b=g.Xd(b))a.B=g.bz(b,c)},H4=function(a,b,c){c=void 0===c?!0:c;
a.player.Ge("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.v(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.D={};0<a.K.length&&(a.K.forEach(function(l){l.dispose()}),a.K.length=0);
a.J=0;if((a.endscreen=b)&&b.elements){c&&fdb(a);c=[];d=new g.sE(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.W().u||(a.u=new g.V({I:"div",S:"ytp-ce-shadow"}),g.sS(a.player,a.u.element,4),a.C=new g.VQ(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=gdb(a,e);if(f){a.j[e.id]=f;a.D[e.id]=e;g.sS(a.player,f.element,4);var h=new g.sE(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);hdb(a,f,e)}else g.ZD(new g.yA("buildEndscreenElement null",
e))}a.player.Je(c);a.Gb()}},fdb=function(a){var b=g.YE(),c=g.ZE();
c&&b&&a.endscreen.visualElement&&g.Iy(g.DP)(void 0,c,b,a.endscreen.visualElement)},gdb=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={I:"div",Ka:["ytp-ce-element","ytp-ce-video"],Y:{tabindex:"0","aria-label":b.PA||"","aria-hidden":"true"},X:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",Y:I4(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",Y:{href:J4(a,b.Ot),tabindex:"-1"},X:[{I:"div",Ka:["ytp-ce-video-title","ytp-webkit-ellipsis"],Y:{dir:g.nq(b.title||"")},xa:b.title},{I:"div",S:b.lC?"ytp-ce-live-video-duration":"ytp-ce-video-duration",xa:b.videoDuration||
void 0}]}]};c=new g.V(a);break;case "PLAYLIST":a={I:"div",Ka:["ytp-ce-element","ytp-ce-playlist"],Y:{tabindex:"0","aria-label":b.PA||"","aria-hidden":"true"},X:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",Y:I4(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",Y:{href:J4(a,b.Ot),tabindex:"-1"},X:[{I:"div",Ka:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],Y:{dir:g.nq(b.title||"")},xa:b.title},{I:"div",S:"ytp-ce-playlist-count",X:[{I:"div",S:"ytp-ce-playlist-icon"},
{I:"div",S:"ytp-ce-playlist-count-text",xa:b.playlistLength||void 0}]}]}]};c=new g.V(a);break;case "CHANNEL":c={I:"div",Ka:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],Y:{tabindex:"0","aria-label":b.PA||"","aria-hidden":"true"},X:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",X:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",X:[{I:"div",
S:"ytp-ce-expanding-overlay-body",X:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",X:[{I:"a",Ka:["ytp-ce-channel-title","ytp-ce-link"],Y:{href:J4(a,b.Ot),target:"_blank",tabindex:"-1",dir:g.nq(b.title||"")},xa:b.title},b.subscribeButton?{I:"div",S:"ytp-ce-subscribe-container",X:[{I:"div",S:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{I:"div",S:"ytp-ce-channel-subscribers-text",xa:b.subscribersText}:"",b.metadata?{I:"div",Ka:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
xa:b.metadata}:""]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",Y:I4(b)}]};c=new g.V(c);var d=g.Me(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.Yp(d,"ytp-ce-subscribe-button");if(a.player.W().u){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.dU(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player);d.appendChild(e.element);a.K.push(e)}break;case "WEBSITE":a={I:"div",Ka:["ytp-ce-element","ytp-ce-website"],Y:{tabindex:"0","aria-label":b.PA||"","aria-hidden":"true"},X:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",X:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",X:[{I:"div",S:"ytp-ce-expanding-overlay-body",X:[{I:"div",
S:"ytp-ce-expanding-overlay-body-padding",X:[{I:"div",S:"ytp-ce-website-title",Y:{dir:g.nq(b.title||"")},xa:b.title},{I:"div",S:"ytp-ce-website-metadata",xa:b.metadata},{I:"a",Ka:["ytp-ce-website-goto","ytp-ce-link"],Y:{href:J4(a,b.Ot),target:"_blank",tabindex:"-1"},xa:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",Y:I4(b)},{I:"div",S:"ytp-ce-expanding-icon",Y:idb(b.iconUrl)}]};c=new g.V(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={I:"div",S:"ytp-ce-merchandise-price-container",
X:[{I:"div",S:"ytp-ce-merchandise-price",xa:b.productPrice}]},b.additionalFeesText&&c.X.push({I:"div",S:"ytp-ce-merchandise-additional-fees",xa:b.additionalFeesText})),a={I:"div",Ka:["ytp-ce-element","ytp-ce-merchandise"],Y:{tabindex:"0","aria-label":b.PA||"","aria-hidden":"true"},X:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",X:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
X:[{I:"div",S:"ytp-ce-expanding-overlay-body",X:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",X:[{I:"div",S:"ytp-ce-merchandise-title",Y:{dir:g.nq(b.title||"")},xa:b.title},c,{I:"div",S:"ytp-ce-merchandise-metadata",xa:b.metadata},{I:"a",Ka:["ytp-ce-merchandise-goto","ytp-ce-link"],Y:{href:J4(a,b.Ot),target:"_blank",tabindex:"-1"},xa:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",Y:I4(b)},{I:"div",S:"ytp-ce-merchandise-invideo-cta-container",X:[{I:"div",S:"ytp-ce-merchandise-invideo-cta",
xa:b.callToAction||void 0}]}]},c=new g.V(a)}b.isPlaceholder&&g.Yp(c.element,"ytp-ce-placeholder");return c},I4=function(a){if(a.mT)var b=a.mT.thumbnails;
return idb(b?b[b.length-1].url:null)},idb=function(a){return a?{style:"background-image: url("+a+")"}:{}},hdb=function(a,b,c){function d(m){m&&(b.Sa("blur",function(){"none"!=m.style.display&&a.ea&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.J+=m;0<a.J?(g.Yp(b.element,"ytp-ce-force-expand"),K4(a,c.id,!0)):(g.$p(b.element,"ytp-ce-force-expand"),g.$p(b.element,"ytp-ce-element-hover"),K4(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Sa("mouseenter",function(){jdb(a,b,c)});
b.Sa("mouseleave",function(){kdb(a,b,c)});
a.player.W().u||b.Sa("click",function(){g.Yp(b.element,"ytp-ce-element-hover")});
b.Sa("click",function(m){ldb(a,c,m)});
b.Sa("keypress",function(m){ldb(a,c,m)});
b.Sa("focus",function(){jdb(a,b,c)});
b.Sa("blur",function(){kdb(a,b,c)});
b.Sa("touchstart",function(){jdb(a,b,c)});
var l=g.Oe("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){g.iP?m.stopPropagation():(m=m||window.event,m.cancelBubble=!0,m.stopPropagation&&m.stopPropagation());g.$p(b.element,"ytp-ce-element-hover");g.$p(b.element,"ytp-ce-force-expand")});
b.Sa("keydown",function(m){a.ea=9===m.keyCode&&!m.shiftKey});
d(g.Oe("ytp-sb-subscribe",b.element));d(g.Oe("ytp-sb-unsubscribe",b.element));b.Sa("focus",f);b.Sa("blur",h)},ldb=function(a,b,c){if(b.Ot&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.Xp(d,"ytp-ce-element");){g.Xp(d,"subscribe-label")&&mdb(a,b);
if(g.Xp(d,"ytp-ce-channel-subscribe"))return;d=g.jf(d)}if(!d||g.Xp(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])kdb(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.f9)mdb(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.de(J4(a,b.Ot)),g.sO(g.Xd(c),void 0,b.sessionData);else{var e=g.lL(a.player.W())||a.player.getVideoData().wd,f=function(){var h=J4(a,b.Ot),l=b.sessionData,m=b.watchEndpoint,n=g.Oy(h);e&&n&&(n.v||n.list)?a.player.Nn(n.v,
l,n.list,!1,void 0,m||void 0):g.qO(h,l)};
mdb(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},J4=function(a,b){a=a.player.W();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.uL(a)+b}else return"";return b},jdb=function(a,b,c){g.Xp(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.Yp(b.element,"ytp-ce-element-hover"):a.player.W().u?(new g.Qp(function(){g.Yp(b.element,"ytp-ce-element-hover")},200)).start():g.Yp(b.element,"ytp-ce-element-hover"),L4(a,c.Y3),K4(a,c.id,!0))},kdb=function(a,b,c){g.$p(b.element,"ytp-ce-element-hover");
g.$p(b.element,"ytp-ce-force-expand");K4(a,c.id,!1)},K4=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.v(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.bq(a.j[e].element,"ytp-ce-element-shadow-show",c)},L4=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||G4(a))c&&c();else{b=ndb(a,b);var e=0,f=!1,h=new g.Qp(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.sC(b[a],d)}},mdb=function(a,b,c){L4(a,b.clickUrls,c);
(a=g.ZE())&&b.l4&&g.JP(a,b.visualElement)},ndb=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(odb(b[d],c));return a},odb=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},pdb=function(a){return"string"===typeof a?a:""},M4=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},qdb=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},N4=function(a){return a.value?a.value:null},O4=function(a){if(!a)return null;
var b=g.de(pdb(a.value));b=g.Xd(b);if(!b)return null;var c=M4(a.target,rdb,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new qdb(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},sdb=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},vdb=function(a){if(!a)return null;
var b=M4(a.type,tdb),c=M4(a.trigger,udb);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=O4(a?a:null);return b?new sdb(b,c,a):null},wdb=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},xdb=function(a,b){return g.xb(a.action,b)},ydb=function(a,b){this.context=a;
this.j=b},zdb=function(a){return a.customMessage?P4("div","iv-card-message",a.customMessage):""},Q4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{I:"div",S:"iv-card-image",Y:{style:a},X:c}},Adb=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.v(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(P4("li","",c.value));return{I:"ul",S:"iv-card-meta-info",X:b}},P4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.nq(c);return{I:a,Y:b,xa:c}},Bdb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.XA&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.XA+");");c.dir=g.nq(a.customMessage);var d=[{I:"span",xa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({I:"span",S:"iv-card-link-icon"}));return{I:"div",Ka:b,Y:c,X:d}},R4=function(a,b,c,d){if(d){b=g.v(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.Pi.click,5)}},Cdb=function(a,b){this.merchant=a;
this.price=b},Ddb=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},Edb=function(a,b){return b?b:Ddb(a)?"current":"new"},S4=function(a,b){g.D.call(this);
var c=this;this.element=a;this.context=b;this.ub=!1;this.Za=new Map;this.fb=new Map;this.context.G.addEventListener(g.uE("annotations_module"),function(d){(d=c.Za.get(d))&&d.apply(c)});
this.context.G.addEventListener(g.vE("annotations_module"),function(d){(d=c.fb.get(d))&&d.apply(c)})},T4=function(a,b,c,d,e,f,h){a.context.j.Sa(b,"click",function(l){a.WI(c,d,e,f||[],h||0,l)});
a.context.j.Sa(b,"touchstart",function(){a.ub=!1});
a.context.j.Sa(b,"touchmove",function(){a.ub=!0})},Fdb=function(a){var b;
return(null==(b=g.Q(a,g.ZM))?0:b.url)?g.Q(a,g.ZM).url:(a=g.Q(a,g.YM))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},U4=function(a,b,c){return{HU:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
cY:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
fI:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},Gdb=function(a,b,c){S4.call(this,b,c);
var d=this;this.G=a;this.eventId=null;this.Ma=this.Pb=this.B=this.isInitialized=!1;this.cards=[];this.Hb=this.V=this.Ja=this.D=this.Ua=this.j=null;this.ma=[];this.qa=this.K=this.gg=this.Ba=null;this.J=0;this.Da=new g.Qp(function(){},c.Z.zi?4E3:3E3);
g.J(this,this.Da);this.qb=new g.Qp(function(){});
g.J(this,this.qb);this.Aa=new ydb(c,function(e,f,h,l,m,n){T4(d,e,f,h,l,m,n)});
this.ea=new g.V({I:"div",S:"iv-drawer",Y:{id:"iv-drawer"},X:[{I:"div",S:"iv-drawer-header",Y:{"aria-role":"heading"},X:[{I:"span",S:"iv-drawer-header-text"},{I:"button",Ka:["iv-drawer-close-button","ytp-button"],Y:{"aria-label":"Hide cards",tabindex:"0"}}]},{I:"div",S:"iv-drawer-content"}]});g.J(this,this.ea);this.C=this.ea.element;this.ib=new g.VQ(this.ea,330);g.J(this,this.ib);this.Ab=g.Oe("iv-drawer-header-text",this.C);this.u=g.Oe("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Pb&&V4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Pb=d.B)&&W4(d)});
this.Oa=new g.lI(this);g.J(this,this.Oa);this.G.addEventListener("videodatachange",this.Ls.bind(this))},Hdb=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){V4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){W4(a)});
var c=b.headerText;g.lf(a.Ab,c);a.V&&a.V.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ba=g.WE(b.trackingParams);a.K=g.WE(b.closeTrackingParams);a.gg=g.WE(b.iconTrackingParams)},Idb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.J,d=a.G.W().experiments.ob("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"simple",teaserText:g.BE(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,Pi:{},Ao:null,fl:e.trackingParams?g.WE(e.trackingParams):null,gg:f&&f.trackingParams?g.WE(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
XA:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};X4(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"simple",teaserText:g.BE(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:Y4(a,c,b,f),sponsored:!1,Pi:U4(f,e,f.command),Ao:f.trackingParams?g.WE(f.trackingParams):null,fl:e.trackingParams?g.WE(e.trackingParams):null,gg:l&&l.trackingParams?g.WE(l.trackingParams):null,imageUrl:Z4(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.BE(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,XA:null,title:f.title?g.BE(f.title):"",customMessage:f.callToAction?g.BE(f.callToAction):"",url:g.Q(f.command,g.ZM).url?O4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.Q(f.command,g.ZM).url}):null,onClickCommand:null};X4(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"collaborator",teaserText:g.BE(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:Y4(a,c,b,e),sponsored:!1,Pi:U4(e,f,e.endpoint),Ao:e.trackingParams?g.WE(e.trackingParams):null,fl:f.trackingParams?g.WE(f.trackingParams):null,gg:l&&l.trackingParams?g.WE(l.trackingParams):null,channelId:g.Q(e.endpoint,g.q3).browseId,customMessage:e.customText?g.BE(e.customText):null,VW:Z4(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.BE(e.channelName):"",metaInfo:[e.subscriberCountText?g.BE(e.subscriberCountText):""],url:O4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.Q(e.endpoint,g.q3).canonicalBaseUrl?g.Q(e.endpoint,g.q3).canonicalBaseUrl:"/channel/"+g.Q(e.endpoint,g.q3).browseId}),onClickCommand:null};X4(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"playlist",teaserText:g.BE(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:Y4(a,c,b,e),sponsored:!1,Pi:U4(e,f,e.action),Ao:e.trackingParams?g.WE(e.trackingParams):null,fl:f.trackingParams?g.WE(f.trackingParams):null,gg:l&&l.trackingParams?g.WE(l.trackingParams):null,XD:Z4(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.BE(e.customMessage):null,playlistVideoCount:g.BE(e.playlistVideoCount),title:e.playlistTitle?g.BE(e.playlistTitle):"",metaInfo:[e.channelName?g.BE(e.channelName):
"",e.videoCountText?g.BE(e.videoCountText):""],url:O4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Fdb(e.action)}),onClickCommand:null};X4(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"video",teaserText:g.BE(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:Y4(a,c,b,e),sponsored:!1,Pi:U4(e,f,e.action),Ao:e.trackingParams?g.WE(e.trackingParams):null,fl:f.trackingParams?g.WE(f.trackingParams):null,gg:l&&l.trackingParams?g.WE(l.trackingParams):null,XD:Z4(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.BE(e.lengthString):null,customMessage:e.customMessage?g.BE(e.customMessage):null,title:e.videoTitle?g.BE(e.videoTitle):"",metaInfo:[e.channelName?g.BE(e.channelName):
"",e.viewCountText?g.BE(e.viewCountText):""],isLiveNow:!!e.badge,url:O4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Fdb(e.action)}),onClickCommand:null};X4(a,b)}}}}}a.J++},Z4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},Y4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},Kdb=function(a,b){if(b=Jdb(a,b))b===a.j&&(a.j=null),a.G.removeCueRange(b.vg.id),g.hf(b.CK),g.Db(a.cards,b),a.SE(),$4(a)},V4=function(a,b,c){if(!a.B){a.ib.show();
a.Ua=new g.Qp(function(){g.Yp(a.context.G.getRootNode(),g.QW.IV_DRAWER_OPEN)},0);
a.Ua.start();a.Oa.T(a.u,"mousewheel",function(h){a.Da.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.B=!0;var d=g.ZE();d&&a.Ba&&a.K&&g.HP(d,[a.Ba,a.K]);b={TRIGGER_TYPE:b};for(var e=g.v(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.sV||(f.sV=!0,Ldb(a.context.logger,f.vg.Pi.HU,b)),d&&g.HP(d,[f.vg.Ao]);x4(a.G);c&&(a.D=new g.Qp(function(){a.Ja=a.V;a.Hb.focus()},330),a.D.start())}},W4=function(a){a.B&&(a.ib.hide(),g.hA(a.Oa),g.$p(a.context.G.getRootNode(),g.QW.IV_DRAWER_OPEN),a.B=!1,x4(a.G),a.D&&a.D.stop(),a.D=new g.Qp(function(){a.Ja&&(a.Ja.focus(),a.Ja=null)},330),a.D.start())},Ndb=function(a){g.Zp(a.wb(),
[g.QW.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.sS(a.G,a.C,5);Mdb(a);a.V=g.Oe("ytp-cards-button",a.G.getRootNode());a.Hb=g.Oe("iv-drawer-close-button",a.C);a.isInitialized=!0},Mdb=function(a){var b=g.Oe("iv-drawer-close-button",a.C);
a.context.j.Sa(b,"click",a.m2,a);a.context.j.Sa(a.u,"touchend",function(){a.Da.start()});
a.context.j.Sa(a.u,"scroll",a.G2,a);a.context.u.subscribe("onHideControls",function(){a.Ma=!0});
a.context.u.subscribe("onShowControls",function(){a.Ma=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Ma=g.Xp(a.G.getRootNode(),"ytp-autohide")});
a.ma.push(g.JC("iv-button-shown",a.w4,a));a.ma.push(g.JC("iv-button-hidden",a.v4,a));a.ma.push(g.JC("iv-teaser-shown",a.IZ,a));a.ma.push(g.JC("iv-teaser-hidden",a.x4,a));a.ma.push(g.JC("iv-teaser-clicked",a.HZ,a))},Odb=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.Q(b.onClickCommand,g.C$a))?void 0:c.targetId)?(a.qa=b,!0):!1},Pdb=function(a,b){a.qa=b;
var c=a.G.getVideoData();if(!c)return!1;c=a.G.N("embeds_web_enable_video_data_refactoring_offline_and_progress_bar")?g.rM(c):c.multiMarkersPlayerBarRenderer;if(null==c?0:c.markersMap)for(var d,e=0;(null==(d=c)?void 0:d.markersMap.length)>e;e++){var f=void 0,h=null==(f=c)?void 0:f.markersMap[e];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.Q(h[0],g.rOa))?void 0:d.timeRangeStartMillis)||0,a.qa=null,!0}return!1},
X4=function(a,b){if(!Odb(a,b)||Pdb(a,b)){var c=Qdb(a,b);
if(c){var d={vg:b,CK:c.element,sV:!1};if(!b.onClickCommand){a.isInitialized||Ndb(a);Kdb(a,b.id);var e=Rdb(a,d);g.Kb(a.cards,e,0,d);c.Ha(a.u,e);a.SE()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.j=d,$4(a),Sdb(a,d),V4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.G.getCurrentTime(),5E3>c&&c>b.startMs&&Tdb(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){Tdb(a,d)}),$4(a))}}},Qdb=function(a,b){switch(b.type){case "simple":a=a.Aa;
var c=b.displayDomain?{I:"div",S:"iv-card-image-text",xa:b.displayDomain}:void 0;var d=Bdb(b);c={I:"div",Ka:["iv-card"],X:[{I:"a",S:"iv-click-target",Y:{href:b.url?N4(b.url)||"":""},X:[Q4(b.imageUrl,c),{I:"div",S:"iv-card-content",X:[P4("h2",void 0,b.title),d]}]}]};c=new g.V(c);R4(a,g.Ne("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Aa;c={I:"div",Ka:["iv-card","iv-card-channel"],X:[{I:"a",Ka:["iv-click-target"],Y:{href:N4(b.url)||"","data-ytid":b.channelId},X:[Q4(b.VW),{I:"div",
S:"iv-card-content",X:[zdb(b),{I:"h2",S:"iv-card-primary-link",xa:b.title},Adb(b)]}]}]};c=new g.V(c);R4(a,g.Ne("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Aa;c={I:"div",Ka:["iv-card","iv-card-playlist"],X:[{I:"a",S:"iv-click-target",Y:{href:N4(b.url)||""},X:[Q4(b.XD,{I:"div",S:"iv-card-image-overlay",X:[{I:"span",S:"iv-card-playlist-video-count",xa:b.playlistVideoCount}]}),{I:"div",S:"iv-card-content",X:[zdb(b),P4("h2","iv-card-primary-link",b.title),Adb(b)]}]}]};c=new g.V(c);
R4(a,g.Ne("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Aa;var e=0!=b.offers.length;c=["iv-card"];d="";var f=Bdb(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({I:"div",S:"iv-card-offer-price",xa:f.price}),f.merchant&&e.push({I:"div",S:"iv-card-offer-merchant",xa:f.merchant}),f={I:"div",X:e});e=b.url?N4(b.url)||"":"";c={I:"div",Ka:c,Y:{tabindex:"0"},X:[{I:"a",Ka:["iv-card-image","iv-click-target"],Y:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{I:"div",S:"iv-card-content",X:[b.sponsored?{I:"div",S:"iv-card-sponsored",X:["Sponsored",{I:"div",S:"iv-ad-info-container",X:[{I:"div",S:"iv-ad-info",xa:"{{adInfo}}"},{I:"div",S:"iv-ad-info-icon-container",X:[{I:"div",S:"iv-ad-info-icon"},{I:"div",S:"iv-ad-info-callout"}]}]}]}:"",{I:"a",S:"iv-click-target",Y:{href:e},X:[P4("h2",d,b.title),f]}]}]};c=new g.V(c);d=g.Ye("span");g.lf(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.Yd(d,"adInfo");R4(a,g.Ne("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Aa;d=b.videoDuration?{I:"span",S:"iv-card-video-duration",xa:b.videoDuration}:void 0;f=b.isLiveNow?{I:"span",Ka:["yt-badge","yt-badge-live"],xa:"LIVE NOW"}:null;e={I:"div",Ka:["iv-card","iv-card-video"],X:[{I:"a",S:"iv-click-target",Y:{href:(null==(c=b.url)?void 0:N4(c))||""},X:[Q4(b.XD,d),{I:"div",S:"iv-card-content",X:[zdb(b),P4("h2","iv-card-primary-link",b.title),Adb(b),f]}]}]};c=new g.V(e);R4(a,g.Ne("iv-click-target",
c.element),b,b.url);b=c;break;default:return null}return b},Rdb=function(a,b){if(0===a.cards.length)return 0;
a=g.Ab(a.cards,function(c){return b.vg.startMs>c.vg.startMs||b.vg.startMs===c.vg.startMs&&b.vg.timestamp>=c.vg.timestamp?!0:!1});
return-1===a?0:a+1},Udb=function(a){return a.j?"productListing"===a.j.vg.type:g.rm(a.cards,function(b){return"productListing"===b.vg.type})},$4=function(a){g.bq(a.G.getRootNode(),"ytp-cards-shopping-active",Udb(a))},Tdb=function(a,b){if(!g.Xp(a.G.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.ZE(),d=a.j?a.j.vg.gg:a.gg;
c&&d&&g.IP(c,[d]);a.j=b;$4(a)}(c=a.isInitialized&&"none"==a.wb().style.display)||(c=a.context.G.getPlayerState(),d=0===c&&0===a.context.G.getCurrentTime(),c=!(1===c||3===c||d));c||b.vg.teaserDurationMs&&a.G.Kz(!0,{teaserText:b.vg.teaserText,durationMs:b.vg.teaserDurationMs,onClickCommand:b.vg.onClickCommand});a.qb.isActive()||((!a.B||!a.Da.isActive()&&a.Ma)&&Sdb(a,b),a.qb.start(910+b.vg.teaserDurationMs))}},Sdb=function(a,b){a.ea.Bb?(b=new C4([0,
a.u.scrollTop],[0,b.CK.offsetTop],600,Zcb),a.context.B.Sa(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Sa(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.wQ(a.ea,!0),a.u.scrollTop=b.CK.offsetTop,g.wQ(a.ea,!1))},a5=function(a){return a.j&&a.j.vg?a.j.vg:a.cards[0]&&a.cards[0].vg?a.cards[0].vg:null},Jdb=function(a,b){return g.xb(a.cards,function(c){return c.vg.id===b})},b5=function(a,b,c){S4.call(this,a,b);
this.annotation=c;this.isActive=!1},Vdb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},c5=function(a,b,c){b5.call(this,a,b,c);
this.u=null;this.K=!1;this.B=null;this.C=!1;this.j=this.J=this.D=null},Wdb=function(a,b){var c=void 0===c?0:c;
var d=Rcb(b).width;g.fn(b,d);c=new Xcb(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,Ycb);g.J(a,c);a.context.B.Sa(c,"begin",function(){g.mn(b,!0)});
c.play()},Zdb=function(a,b){if(b.channel_name){var c=a.createElement({I:"div",
Ka:["iv-branding-context-name"],xa:b.channel_name}),d=a.createElement({I:"div",Ka:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.dU(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.G),a.j.Ha(d));var f=a.createElement({I:"div",Ka:["iv-branding-context-subscribe-caret"]}),h=a.createElement({I:"div",Ka:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.mn(h,!1);var l=a.createElement({I:"div",Ka:["branding-context-container-outer"]});l.appendChild(h);g.$m(l,"right",b.image_width+"px");g.$e(a.wb(),l);a.B=new g.Qp(function(){Xdb(a,h,l)},500);
g.J(a,a.B);a.context.j.Sa(a.wb(),"mouseover",function(){Ydb(a,h,l,f,b.image_height)});
a.context.j.Sa(a.wb(),"mouseout",function(){a.B.start()})}},Ydb=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.ln(b);a.j||(b.style.width=g.en(f.width,!0),c.style.width=g.en(f.width,!0));g.$m(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.$m(d,"right","1px");a.C=!0;g.mn(b,!0);a.D=new g.Qp(function(){g.Yp(this.wb(),"iv-branding-active")},0,a);
a.D.start()}},Xdb=function(a,b,c){g.$p(a.wb(),"iv-branding-active");
a.J=new g.Qp(function(){g.mn(b,!1);a.j||(c.style.width=g.en(0,!0))},250);
a.J.start();a.C=!1},$db=function(a,b,c,d,e,f,h){this.j=a;
this.B=b;this.Z=c;this.videoData=d;this.logger=e;this.G=f;this.u=h},aeb=function(a,b,c){b5.call(this,a,b,c);
var d=this;this.V=this.isCollapsed=this.ea=!1;this.J=5E3;this.u=this.B=this.j=this.C=null;this.K=this.createElement({I:"div",Ka:["iv-promo-contents"]});this.D=new g.Qp(function(){d.j.setAttribute("aria-hidden","true");g.mn(d.B,!1);g.mn(d.u,!0)},700,this);
g.J(this,this.D)},ceb=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.J=b.collapsedelay_ms||a.J;var d=["iv-promo","iv-promo-inactive"];a.wb().setAttribute("aria-hidden","true");a.wb().setAttribute("aria-label","Promotion");a.wb().tabIndex=0;var e=a.annotation.jf(),f=b.image_url;if(f){var h=a.createElement({I:"div",Ka:["iv-promo-img","iv-click-target"]});f=a.createElement({I:"img",Y:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?
(f=a.createElement({I:"span",S:"iv-promo-video-duration",xa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({I:"span",S:"iv-promo-playlist-length",xa:b.playlist_length.toString()}),h.appendChild(f));e&&T4(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({I:"a",S:"iv-promo-txt"}),g.le(f,N4(e)),a.j=f):a.j=a.createElement({I:"div",S:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({I:"p",X:[{I:"strong",xa:b.text_line_1}]});
var m=a.createElement({I:"p",X:[{I:"span",S:"iv-promo-link",xa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({I:"button",Ka:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({I:"button",Ka:["iv-button","iv-promo-button"],X:[{I:"span",S:"iv-button-content",xa:f}]});var p=a.createElement({I:"div",S:"iv-promo-button-container"});p.appendChild(f);e&&T4(a,a.wb(),e,a.annotation.id,b.session_data,void 0,c)}g.Yp(a.j,"iv-click-target");
e&&T4(a,a.j,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({I:"p",X:[{I:"span",xa:b.text_line_1}]}),m=a.createElement({I:"p",X:[{I:"strong",xa:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({I:"span",Ka:["yt-badge","iv-promo-badge-live"],xa:"LIVE NOW"})),g.Yp(a.j,"iv-click-target"),e&&T4(a,a.j,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.j.appendChild(l);m&&a.j.appendChild(m);a.K.appendChild(a.j);p&&a.K.appendChild(p);
c=a.createElement({I:"div",S:"iv-promo-actions"});a.u=a.createElement({I:"button",Ka:["iv-promo-expand","ytp-button"]});a.u.title="Expand";a.context.j.Sa(a.u,"click",function(q){beb(a,5E3,q)});
c.appendChild(a.u);g.mn(a.u,!1);a.context.j.Sa(a.wb(),"mouseover",a.C3,a);a.context.j.Sa(a.wb(),"mouseout",a.B3,a);a.context.j.Sa(a.wb(),"touchend",function(q){beb(a,5E3,q)});
a.B=a.createElement({I:"button",Ka:["iv-promo-close","ytp-button"]});a.B.title="Close";a.context.j.Sa(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.x3:a.w3,a);c.appendChild(a.B);g.Zp(a.wb(),d);h&&(g.$e(a.wb(),h),n&&h.appendChild(n));g.$e(a.wb(),a.K);g.$e(a.wb(),c)},beb=function(a,b,c){c.stopPropagation();
deb(a);eeb(a,b);a.j.focus()},feb=function(a){a.isCollapsed||a.V||a.C||(g.Yp(a.wb(),"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},deb=function(a){a.D.stop();
a.isCollapsed&&(g.aq(a.wb(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.mn(a.u,!1),g.mn(a.B,!0))},eeb=function(a,b){a.C||(a.C=g.Lf(function(){geb(this);
feb(this)},b,a))},geb=function(a){a.C&&(g.La.clearTimeout(a.C),a.C=null)},heb=function(a){this.G=a},Ldb=function(a,b,c){b&&(c?d5(a,b.map(function(d){return g.Fp(d,c)})):d5(a,b))},d5=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.v(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.sC(m,f);d&&(e++,0!==d&&a.G.sendVideoStatsEngageEvent(d,f))},ieb=function(a){g.uT.call(this,a);
var b=this;this.ea=this.K=!1;this.loadNumber=0;this.J={};this.logger=new heb(this.player);this.C=new g.lI(this);this.D=this.ww=null;this.events=new g.lI(this);this.jh=this.V=this.j=null;this.ma=[];g.J(this,this.C);this.C.T(this.player,"onVideoAreaChange",function(){b.oa("onVideoAreaChange")});
this.C.T(this.player,"onHideControls",function(){b.oa("onHideControls")});
this.C.T(this.player,"onShowControls",function(){b.oa("onShowControls")});
this.C.T(this.player,"resize",function(d){b.oa("resize",d)});
this.C.T(this.player,"presentingplayerstatechange",function(d){b.oa("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.JZ,this);this.subscribe("resize",this.YG,this);this.player.W().Ja.subscribe("vast_info_card_add",this.EW,this);g.J(this,this.events);this.qa=this.createElement({I:"div",S:"video-custom-annotations"});this.u=new g.V({I:"div",Ka:["ytp-player-content","ytp-iv-player-content"]});g.J(this,this.u);g.sS(this.player,this.u.element,4);this.u.hide();this.B=new g.V({I:"div",Ka:["ytp-iv-video-content"]});g.J(this,this.B);a=this.createElement({I:"div",S:"video-annotations"});
a.appendChild(this.qa);this.B.element.appendChild(a);this.hw()&&this.load();var c=this.createElement({I:"style"});(g.Le("HEAD")[0]||document.body).appendChild(c);g.ob(this,function(){g.hf(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},jeb=function(a){a=a.createElement({I:"div",
Ka:["annotation","annotation-type-custom"]});g.mn(a,!1);return a},keb=function(a,b){b=!b.isCued()&&!g.BO(b,1024);
g.wQ(a.u,b);g.wQ(a.B,b)},leb=function(a,b,c){a.K=!0;
a.D=g.bz(b,c)},meb=function(a,b){for(var c={},d=g.v(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Ra(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(meb(a,e))}return c},qeb=function(a){var b=a.player.getVideoData();
if(b.Oa){var c=a.player.W().Ja.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.Wy(h)&&h.responseXML?h.responseXML:null)&&neb(a,h)}};
g.GA()&&(d.onFinish=oeb(a,d.onFinish));d.postParams={ic_only:"1"};peb(d,c);a.K=!0;g.bz(b.Oa,d)}}},peb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.ZA&&(a.postParams.ic_coll=b.ZA);b.DK&&(a.postParams.ic_xml=b.DK);b.iI&&(a.postParams.ic_track=b.iI)},reb=function(a){var b=new g.V({I:"div"});
g.mn(b.element,!1);var c=new Gdb(a.player,b.element,e5(a));g.J(c,b);b.Ha(a.u.element);c.MD();return c},e5=function(a){if(!a.V){var b=new $cb(a);
g.J(a,b);var c=new g.nl(a);g.J(a,c);a.V=new $db(b,c,a.player.W(),a.player.getVideoData(),a.logger,a.player,a.zi)}return a.V},neb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.ZE();if(e){var f=g.YE();f&&g.Iy(g.kAa)(void 0,e,f,[g.WE(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=meb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=M4(f.type,seb),p=M4(f.style,teb),q=pdb(f.data),t=0!==q.length?JSON.parse(q):{};var u=f.action;f=vdb;if(null==u)var y=null;else if(g.Pa(u)){l=[];for(var B=g.v(u),G=B.next();!G.done;G=B.next()){var M=f(G.value);
M&&l.push(M)}y=l}else{var N=f(u);y=N?[N]:[]}e=m&&n?new wdb(m,n,p,y,t):null}else e=null}catch(la){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var H=jeb(f),U=null;switch(l.type){case "branding":if(f.player.W().Ed)break;f.u.element.appendChild(H);U=new c5(H,e5(f),l);break;case "promotion":g.sS(f.player,H,4),U=new aeb(H,e5(f),l)}U&&U.MD();if(f=U)g.J(a,f),a.J[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=reb(a),g.J(a,a.j));if("card"===e.type){c=a.j;var aa=e&&e.data&&e.data.card_type;
f=e.data;if(aa)switch(l=f.tracking||{},l={HU:l.impression,click:l.click,close:l.close,cY:l.teaser_impression,fI:l.teaser_click},H=f.tracking_params||{},U=null,aa){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Pi:l,Ao:H.card?g.WE(H.card):null,fl:H.teaser?g.WE(H.teaser):null,gg:H.icon?g.WE(H.icon):null,channelId:f.channel_id,
customMessage:f.custom_message?f.custom_message:null,VW:f.image_url,title:f.title,metaInfo:f.meta_info,url:O4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};X4(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Pi:l,Ao:H.card?g.WE(H.card):null,fl:H.teaser?
g.WE(H.teaser):null,gg:H.icon?g.WE(H.icon):null,XD:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:O4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};X4(c,e);break;case "productListing":f.signin_url&&(U=O4({target:"current",value:f.signin_url}));aa=[];for(var da=f.offers||[],ua=0;ua<da.length;ua++)aa.push(new Cdb(g.Ee(da[ua].merchant),g.Ee(da[ua].price)));
e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Pi:l,Ao:H.card?g.WE(H.card):null,fl:H.teaser?g.WE(H.teaser):null,gg:H.icon?g.WE(H.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,XA:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:O4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),B9a:U,A9a:f.signin_title?f.signin_title:void 0,z9a:f.signin_message?f.signin_message:void 0,offers:aa,onClickCommand:null};X4(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Pi:l,Ao:H.card?g.WE(H.card):
null,fl:H.teaser?g.WE(H.teaser):null,gg:H.icon?g.WE(H.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,XA:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:O4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};X4(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,
startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Pi:l,Ao:H.card?g.WE(H.card):null,fl:H.teaser?g.WE(H.teaser):null,gg:H.icon?g.WE(H.icon):null,XD:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:O4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null},X4(c,e)}}else Hdb(a.j,e);c=!0}}c&&
(x4(a.player),a.YG())},ueb=function(a,b){var c=!1;
a.j||(a.j=reb(a),g.J(a,a.j));for(var d=g.v(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(Idb(a.j,e.cardRenderer),c=!0);if(c){var f;null!=(f=a.player.getVideoData())&&g.uN(f)||(c=a.j,d=b.headerText?g.BE(b.headerText):"",g.lf(c.Ab,d),c.V&&c.V.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ba=b.trackingParams?g.WE(b.trackingParams):null,c.K=b.closeButton.infoCardIconRenderer.trackingParams?g.WE(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.gg=b.icon.infoCardIconRenderer.trackingParams?g.WE(b.icon.infoCardIconRenderer.trackingParams):null,a.YG());x4(a.player)}},veb=function(a,b,c,d,e){if(!a.player.W().Ed){var f=[];
b.navigationEndpoint&&g.Q(b.navigationEndpoint,g.q3)&&g.Q(b.navigationEndpoint,g.q3).browseId&&f.push(new sdb("openUrl","click",new qdb("/channel/"+g.Q(b.navigationEndpoint,g.q3).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.Q(b.subscribeButton,
g.nN)){d.channel_id=g.Q(b.subscribeButton,g.nN).channelId;var l;b=g.Q(b.subscribeButton,g.nN);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.BE(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.BE(b.subscriberCountText))):(b.subscriberCountText&&(e=g.BE(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.BE(b.subscriberCountWithSubscribeText)));var m,n=(null==(m=g.Q(null==(l=b.signInEndpoint)?void 0:l.commandMetadata,g.r3))?void 0:m.url)||"";l={subscribeText:g.BE(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.BE(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new wdb(c,"branding","branding",f,d);l=jeb(a);a.u.element.appendChild(l);f=new c5(l,e5(a),f);f.MD();g.J(f,f);a.J[c]=f}},oeb=function(a,b){return function(){var c=g.Ea.apply(0,arguments);
a.isDisposed()||a.ma.push(g.Ip.Ai(function(){b.apply(null,g.oa(c))}))}},web=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.lS.prototype.Kz=g.ca(18,function(a,b){var c=g.IT(this.yb());c&&c.Kz(a,b)});
var z4={},A4=null;g.ab(C4,g.jq);g.k=C4.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.u;else if(this.hd())return!1;B4(this);this.startTime=a=g.Ya();-1==this.j&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.C=this.startTime;this.progress||this.SG();this.Il("play");-1==this.j&&this.Il("resume");this.j=1;var b=g.Ua(this);b in z4||(z4[b]=this);Tcb();Ucb(this,a);return!0};
g.k.stop=function(a){B4(this);this.j=0;a&&(this.progress=1);Vcb(this,this.progress);this.Il("stop");this.Kq()};
g.k.pause=function(){this.hd()&&(B4(this),this.j=-1,this.Il("pause"))};
g.k.ra=function(){0==this.j||this.stop(!1);this.Il("destroy");C4.Hf.ra.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.VI=function(){this.Il("animate")};
g.k.Il=function(a){this.dispatchEvent(new Wcb(a,this))};
g.ab(Wcb,g.tb);g.ab(D4,C4);D4.prototype.B=function(){};
D4.prototype.VI=function(){this.B();D4.Hf.VI.call(this)};
D4.prototype.Kq=function(){this.B();D4.Hf.Kq.call(this)};
D4.prototype.SG=function(){this.B();D4.Hf.SG.call(this)};
g.ab(Xcb,D4);Xcb.prototype.B=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.x($cb,g.D);g.k=$cb.prototype;g.k.Sa=function(a,b,c,d){c=(0,g.Wa)(c,d||this.u);a=g.$z(a,b,c);this.j.push(a);return a};
g.k.vG=function(a,b,c,d){c=(0,g.Wa)(c,d||this.u);a=g.hna(a,b,c);this.j.push(a);return a};
g.k.Ic=function(a){g.aA(a);g.Db(this.j,a)};
g.k.Gf=function(){g.aA(this.j);this.j.length=0};
g.k.ra=function(){this.Gf();g.D.prototype.ra.call(this)};g.x(cdb,g.uT);g.k=cdb.prototype;g.k.load=function(){g.uT.prototype.load.call(this);if(!G4(this)){var a=g.Bya(this.player.getVideoData());a?(a=bdb(a,ddb(this)),H4(this,a,!1)):edb(this)}};
g.k.unload=function(){H4(this,null);this.B&&(this.B.abort(),this.B=null);g.uT.prototype.unload.call(this)};
g.k.wh=function(a,b){return G4(this)?"loadCustomEndscreenRenderer"===a?(a=bdb(b,"new"),H4(this,a),!0):null:null};
g.k.getOptions=function(){return G4(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Gb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<xeb.length;f++){var h=Math.abs(b.width-xeb[f]);if(-1===e||d>=h)e=f,d=h}d=yeb[e];this.u&&g.$m(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.D[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.kn(e.element,m,f);g.fn(e.element,n,p);g.aq(e.element,zeb);256<m||256<f?g.Yp(e.element,"ytp-ce-large-round"):96<m||96<f?g.Yp(e.element,"ytp-ce-medium-round"):g.Yp(e.element,"ytp-ce-small-round");g.aq(e.element,Aeb);m=h.left+h.width/2;h=h.top+l/2;g.Yp(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.aq(e.element,yeb);g.Yp(e.element,d);(e=g.Me(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.$m(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())L4(this,this.endscreen.impressionUrls),(a=g.ZE())&&this.endscreen.visualElement&&g.GP(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.D[a];g.Yp(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.Yp(b,"ytp-ce-shown");L4(this,c.impressionUrls);(b=g.ZE())&&g.GP(b,c.visualElement);this.player.W().J&&this.player.Pa("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.$p(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.$p(b,"ytp-ce-shown");this.player.W().J&&this.player.Pa("endscreenelementhidden",a)}};
g.k.O7=function(a){var b=this;a.target===window&&(new g.Qp(function(){for(var c=g.v(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.aq(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var xeb=[346,426,470,506,570,640,853,1280,1920],yeb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Aeb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],zeb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var rdb={cna:"current",XKa:"new"};var tdb={CLOSE:"close",wOa:"openUrl",SUBSCRIBE:"subscribe"},udb={Gla:"click",CLOSE:"close",nxa:"hidden",gTa:"rollOut",hTa:"rollOver",DUa:"shown"};wdb.prototype.jf=function(){var a=xdb(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var teb={Rga:"anchored",hZ:"branding",CHANNEL:"channel",Sma:"cta",qxa:"highlightText",lBa:"label",PLAYLIST:"playlist",PQa:"popup",iXa:"speech",SUBSCRIBE:"subscribe",i_a:"title",VIDEO:"video",d5a:"website"},seb={hZ:"branding",Dja:"card",Yoa:"drawer",pxa:"highlight",gHa:"marker",bSa:"promotion",TEXT:"text",C6a:"widget"};g.x(S4,g.D);g.k=S4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.sE(a,b,{id:c,namespace:"annotations_module"});d&&this.Za.set(a,d);e&&this.fb.set(a,e);this.context.G.Je([a])};
g.k.MD=function(){this.context.u.subscribe("resize",this.SE,this)};
g.k.wb=function(){return this.element};
g.k.WI=function(a,b,c,d,e,f){if(this.ub)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.hf(this.wb())};
g.k.SE=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=N4(a);if(f){var h=Edb(f,a.target),l=function(){a.j&&e.context.G.pauseVideo();var m=e.context.videoData.wd||!1,n=g.Oy(f||"");m&&n&&(n.v||n.list)?e.context.G.Nn(n.v,b,n.list,!1):g.sO(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);d5(this.context.logger,c,l,d);Ddb(f)||(c=g.ZE(),d=b.itct,c&&d&&g.JP(c,g.WE(d)))}};
g.k.ra=function(){this.Za.clear();this.fb.clear();g.D.prototype.ra.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.J(this,a);return a.element};g.x(Gdb,S4);g.k=Gdb.prototype;g.k.Ls=function(){this.qa&&X4(this,this.qa)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.G.getRootNode())?(a=g.ln(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.SE=function(){var a=this.isAvailable();g.mn(this.wb(),a);g.bq(this.context.G.getRootNode(),g.QW.IV_DRAWER_ENABLED,a);x4(this.G)};
g.k.destroy=function(){this.G.Kz(!1);try{this.G.getRootNode().removeChild(this.C)}catch(a){}g.KC(this.ma);g.hA(this.Oa);this.Ua&&this.Ua.dispose();this.D&&this.D.dispose();S4.prototype.destroy.call(this)};
g.k.m2=function(){if(this.B){d5(this.context.logger,a5(this).Pi.close);var a=g.ZE();a&&this.K&&g.JP(a,this.K);W4(this)}};
g.k.G2=function(){g.bq(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.w4=function(){var a=g.ZE(),b=a5(this);b=b?b.gg:this.gg;a&&b&&g.HP(a,[b])};
g.k.v4=function(){var a=g.ZE(),b=a5(this);b=b?b.gg:this.gg;a&&b&&g.IP(a,[b])};
g.k.IZ=function(){var a=a5(this);d5(this.context.logger,a.Pi.cY);var b=g.ZE();b&&a&&g.HP(b,[a.fl,a.gg])};
g.k.x4=function(){var a=g.ZE(),b=a5(this);a&&b&&g.IP(a,[b.fl])};
g.k.HZ=function(a){var b=a5(this),c=g.ZE();this.j?a?(a=this.context.logger,d5(a,b.Pi.fI),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.fl&&g.JP(c,b.fl)):(a=this.context.logger,d5(a,b.Pi.fI),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.gg&&g.JP(c,b.gg)):(a=this.context.logger,d5(a,b.Pi.fI),a.G.sendVideoStatsEngageEvent(4,void 0),c&&this.gg&&g.JP(c,this.gg))};g.x(b5,S4);b5.prototype.MD=function(){S4.prototype.MD.call(this);Vdb(this)};
b5.prototype.show=function(){S4.prototype.show.call(this);var a=g.ZE(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.HP(a,[g.WE(b.itct)])};
b5.prototype.hide=function(){S4.prototype.hide.call(this);var a=g.ZE(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.IP(a,[g.WE(b.itct)])};g.x(c5,b5);
c5.prototype.show=function(){if(!this.isActive){b5.prototype.show.call(this);if(!this.K){g.Yp(this.wb(),"iv-branding");var a=this.annotation.data;this.u=this.createElement({I:"img",Ka:["branding-img","iv-click-target"],Y:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.mn(this.u,!1);var b=this.createElement({I:"button",Ka:["branding-img-container","ytp-button"]});b.appendChild(this.u);this.wb().appendChild(b);var c=this.annotation.jf();c&&T4(this,b,
c,this.annotation.id,a.session_data);Zdb(this,a);this.K=!0}g.mn(this.wb(),!0);this.isActive=!0;this.u&&(Wdb(this,this.u),g.Yp(this.context.G.getRootNode(),"ytp-branding-shown"))}};
c5.prototype.hide=function(){this.isActive&&(b5.prototype.hide.call(this),g.mn(this.wb(),!1),this.isActive=!1,g.$p(this.context.G.getRootNode(),"ytp-branding-shown"))};
c5.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);b5.prototype.destroy.call(this)};g.x(aeb,b5);g.k=aeb.prototype;g.k.show=function(){this.isActive||(b5.prototype.show.call(this),this.ea||(ceb(this),this.ea=!0),g.mn(this.wb(),!0),g.Lf(function(){g.$p(this.wb(),"iv-promo-inactive")},100,this),this.wb().removeAttribute("aria-hidden"),this.isActive=!0,geb(this),deb(this),eeb(this,this.J))};
g.k.hide=function(){this.isActive&&(g.Yp(this.wb(),"iv-promo-inactive"),this.isActive=!1,this.wb().setAttribute("aria-hidden","true"))};
g.k.WI=function(a,b,c,d,e,f){return this.isCollapsed?!1:b5.prototype.WI.call(this,a,b,c,d,e,f)};
g.k.C3=function(a){this.V=!0;beb(this,500,a)};
g.k.B3=function(){this.V=!1;feb(this)};
g.k.w3=function(a){a.stopPropagation();this.hide()};
g.k.x3=function(a){a.stopPropagation();geb(this);this.isCollapsed=!0;g.Yp(this.wb(),"iv-promo-collapsed-no-delay");this.D.start()};
g.k.destroy=function(){this.D.dispose();b5.prototype.destroy.call(this)};g.x(ieb,g.uT);g.k=ieb.prototype;g.k.wh=function(a,b){if(!web(this.player.W().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.g8a(b))&&neb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(Kdb(this.j,b),x4(this.player)),!0}return null};
g.k.getOptions=function(){return web(this.player.W().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.hw=function(){var a=this.player.W(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return b.wd&&a.ma||g.fS(this.player.app)?!1:1===c&&!b.PR||a.Ja.get(b.videoId)||g.vN(b)||g.wN(b)?!0:!1};
g.k.YG=function(){if(this.B){var a=this.player.kb().getVideoContentRect(!0);g.kn(this.B.element,a.width,a.height);g.fn(this.B.element,a.left,a.top)}if(this.j){var b=this.player.Bk();a=this.j;b=b.width;g.bq(a.C,"iv-drawer-small",426>=b);g.bq(a.C,"iv-drawer-big",1280<=b)}};
g.k.JZ=function(a){keb(this,a.state);g.BO(a.state,2)&&(this.rk()&&this.zo()&&2!==this.player.getPresentingPlayerType()&&this.Lz(!1),this.Kz(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.D=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.Wy(h)&&h.responseXML?h.responseXML:null)&&(neb(b,h),g.Yp(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.uT.prototype.load.call(this);keb(this,this.player.Ib());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.GA()&&(a=oeb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.D=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.W().Ja.get(d);f&&peb(e,f);f=f&&(f.DK||f.ZA);if(!c.nA||f)c.Oa?leb(this,c.Oa,e):(this.ww=function(){if(!b.K)b.onVideoDataChange(e);var h=b.player.getVideoData();if((null==h?0:g.uN(h))&&!b.ea){var l,m;if(h=null==(l=h.kd)?void 0:null==(m=l.cards)?void 0:m.cardCollectionRenderer)b.ea=!0,ueb(b,h),h.headerText&&b.jh&&(l=g.BE(h.headerText),b.jh.setAttribute("title",l))}},this.player.addEventListener("videodatachange",
this.ww));
g.sS(this.player,this.B.element,4);this.YG();(f=g.vN(c))&&ueb(this,f);(f=g.wN(c))&&f.featuredChannel&&veb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.jh=g.Oe("ytp-cards-button",this.player.getRootNode())};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Oa&&leb(this,b.Oa,a)};
g.k.unload=function(){this.player.Ge("annotations_module");for(var a=g.v(Object.keys(this.J)),b=a.next();!b.done;b=a.next())this.J[b.value].destroy();this.V=null;this.j&&(this.j.destroy(),this.j=null,x4(this.player));this.K=!1;this.D&&(this.D.abort(),this.D=null);this.ea=!1;this.J={};this.u.hide();g.uT.prototype.unload.call(this);this.B.detach();this.ww&&(this.player.removeEventListener("videodatachange",this.ww),this.ww=null)};
g.k.EW=function(a){a===this.player.getVideoData().videoId&&(this.loaded?qeb(this):this.load())};
g.k.rk=function(){var a;return(null==(a=this.j)?void 0:a.isAvailable())||this.ea};
g.k.zo=function(){return!!this.j&&this.j.B};
g.k.Lz=function(a,b,c){b=void 0===b?!1:b;this.rk();this.j&&(a?c?V4(this.j,c,b):V4(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):W4(this.j))};
g.k.Kz=function(a,b){this.player.oa(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.ra=function(){this.player.W().Ja.unsubscribe("vast_info_card_add",this.EW,this);g.$p(this.player.getRootNode(),g.QW.IV_DRAWER_OPEN);for(var a=this.ma,b=g.Ip,c=0,d=a.length;c<d;c++)b.Jm(a[c]);this.ma.length=0;g.uT.prototype.ra.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.J(this,a);return a.element};g.tT("annotations_module",ieb);g.tT("creatorendscreen",cdb);})(_yt_player);
